# Generated by Django 5.1.6 on 2025-03-11 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('oxygen_level', models.FloatField()),
                ('co2_level', models.FloatField()),
                ('light_illumination', models.FloatField()),
            ],
        ),
    ]
