# Generated by Django 5.1.6 on 2025-03-11 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='co2_level',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
