# Generated by Django 5.1.6 on 2025-03-14 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0002_alter_sensordata_co2_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fan_mode', models.CharField(choices=[('auto', 'Auto'), ('on', 'On'), ('off', 'Off')], default='auto', max_length=10)),
                ('water_mode', models.CharField(choices=[('auto', 'Auto'), ('on', 'On'), ('off', 'Off')], default='auto', max_length=10)),
            ],
        ),
    ]
