# Generated by Django 5.1.6 on 2025-03-22 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0003_controlstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlstate',
            name='fan_is_running',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='controlstate',
            name='last_water_dispense',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
