# Generated by Django 5.1.6 on 2025-03-25 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0005_remove_controlstate_fan_is_running'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlstate',
            name='fan_is_running',
            field=models.BooleanField(default=False),
        ),
    ]
